In [1]:
%load_ext autoreload

In [2]:
import sys

sys.path.append("/home/aurimas/coding/price-volume-mix/resources")
sys.path.append("/home/aurimas/coding/price-volume-mix/package")

In [3]:
from datasets.olist import sales_data

In [4]:
import polars as pl
import polars.selectors as cs
import tabulate
import numpy as np
import altair as alt
import importlib as imp
import itertools as itt

alt.renderers.set_embed_options(actions=False)

RendererRegistry.enable('default')

In [5]:
%aimport pvm
import pvm
import pvm.fields as pvmf
import pvm.calculations as pvmc
import pvm.charts as pmv_charts

imp.reload(pvmf)
imp.reload(pvmc)
pass

In [6]:
totals = (
    sales_data.group_by(["year"])
    .agg(
        pl.sum("revenue").alias("Total revenue ('000)") / 1000,
        pl.sum("quantity").alias("Total products sold ('000)") / 1000,
    )
    .with_columns(
        (pl.col("Total revenue ('000)") / pl.col("Total products sold ('000)")).alias(
            "Average price"
        )
    )
    .melt(id_vars="year", variable_name="KPI")
    .pivot(index="KPI", values="value", columns="year")
    .with_columns(
        (pl.col("2018") - pl.col("2017")).alias("change"),
        ((pl.col("2018") - pl.col("2017")) / pl.col("2017") * 100).alias("% change"),
    )
)


def print_table(df: pl.DataFrame, round=1):
    print(
        tabulate.tabulate(
            df.to_pandas().round(round),
            headers=df.columns,
            tablefmt="simple",
            showindex=False,
        )
    )

In [7]:
# | label: olist-totals
# | fig-cap: "Olist revenue, volume and average price in 2017-2018"
# | fig-subcap: ""
# | fig-alt: ""
# | layout-ncol: 1

print_table(totals)

KPI                           2017    2018    change    % change
--------------------------  ------  ------  --------  ----------
Total revenue ('000)        6805.5  8364.3    1558.8        22.9
Total products sold ('000)    48.7    59.6      11          22.5
Average price                139.8   140.2       0.4         0.3

Looks like Olist was doing great - its revenue was up 1.6M (23%), mostly because it sold more products (though average price also went up a bit).

### PVM calculations

Let's try the intuitive approach: holding the other factor constant.

In [8]:
# | label: holding-other-constant
# | fig-cap: "Calculating price and volume effects"
# | fig-subcap: ""
# | fig-alt: ""
# | layout-ncol: 1

pandas_totals = totals.to_pandas().set_index("KPI")

p2017 = pandas_totals.loc["Average price", "2017"]
p2018 = pandas_totals.loc["Average price", "2018"]
q2017 = pandas_totals.loc["Total products sold ('000)", "2017"]
q2018 = pandas_totals.loc["Total products sold ('000)", "2018"]
r2017 = pandas_totals.loc["Total revenue ('000)", "2017"]
r2018 = pandas_totals.loc["Total revenue ('000)", "2018"]

price_effect = (p2018 - p2017) * q2017
volume_effect = (q2018 - q2017) * p2017

print(f"Actual change in revenue: {(r2018 - r2017):.2f}")
print(f"Price effect: {price_effect:.2f}")
print(f"Volume effect: {volume_effect:.2f}")
print(f"Total change (price + volume effect): {price_effect + volume_effect:.2f}")

Actual change in revenue: 1558.78
Price effect: 20.56
Volume effect: 1533.58
Total change (price + volume effect): 1554.14

The correct formula:

In [9]:
# | label: basic-pvm-calculation
# | fig-cap: "Calculating price and volume on an aggregate level"
# | fig-subcap: ""
# | fig-alt: ""
# | layout-ncol: 1

price_effect = (p2018 - p2017) * q2018
volume_effect = (q2018 - q2017) * p2017

print(f"Actual change in revenue: {(r2018 - r2017):.2f}")
print(f"Price effect: {price_effect:.2f}")
print(f"Volume effect: {volume_effect:.2f}")
print(f"Total change (price + volume effect): {price_effect + volume_effect:.2f}")

Actual change in revenue: 1558.78
Price effect: 25.20
Volume effect: 1533.58
Total change (price + volume effect): 1558.78

In [10]:
# | label: basic-pvm-chart
# | fig-cap: "Fancy, but largely useless PVM waterfall chart"
# | fig-subcap: ""
# | fig-alt: ""
# | width: 100%
# | fig-align: center
# | layout-ncol: 1

pmv_charts.waterfall(
    [
        ("2017", True, r2017),
        ("Price effect", False, price_effect),
        ("Volume effect", False, volume_effect),
        ("2018", True, 0),
    ]
).properties(width=650, title="Olist revenue bridge 2017-2018")

alt.LayerChart(...)

## Analysis by geography

In [11]:
# | label: basic-geo-eda
# | fig-cap: "Price, volume and revenue trends by state - % vs. previous year"
# | fig-subcap: ""
# | fig-alt: ""
# | width: 100%
# | fig-align: center
# | layout-ncol: 1

totals_by_state = (
    sales_data.group_by(["year", "customer_state"])
    .agg(
        pl.sum("revenue").alias("Total revenue ('000)") / 1000,
        pl.sum("quantity").alias("Total products sold ('000)") / 1000,
    )
    .with_columns(
        (pl.col("Total revenue ('000)") / pl.col("Total products sold ('000)")).alias(
            "Average price"
        )
    )
    .melt(id_vars=["year", "customer_state"], variable_name="KPI")
    .pivot(index=["customer_state", "KPI"], values="value", columns=["year"])
    .with_columns(
        (pl.col("2018") - pl.col("2017")).alias("change"),
        ((pl.col("2018") - pl.col("2017")) / pl.col("2017") * 100).alias("% change"),
    )
)

alt.Chart(totals_by_state).mark_bar().encode(
    alt.X("customer_state", axis=alt.Axis(labelAngle=0)),
    y="% change",
    row="KPI",
    tooltip=alt.Tooltip("% change"),
    color=alt.condition(
        alt.datum["% change"] < 0, alt.ColorValue("red"), alt.ColorValue("green")
    ),
).properties(
    width=600, height=100, title="Percentage changes in KPIs by state"
).resolve_scale(y="independent")

alt.Chart(...)

In [12]:
# | label: basic-geo-eda-absolute
# | fig-cap: "Price, volume and revenue trends by state - absolute change vs. previous year"
# | fig-subcap: ""
# | fig-alt: ""
# | width: 100%
# | fig-align: center
# | layout-ncol: 1

alt.Chart(totals_by_state).mark_bar().encode(
    alt.X("customer_state", axis=alt.Axis(labelAngle=0)),
    y="change",
    row="KPI",
    tooltip=alt.Tooltip("change"),
    color=alt.condition(
        alt.datum["change"] < 0, alt.ColorValue("red"), alt.ColorValue("green")
    ),
).properties(
    width=550, height=100, title="Absolute changes in KPIs by state"
).resolve_scale(y="independent")

alt.Chart(...)

In [13]:
# produce a dataset with data aggregated by year & state
kpis_by_year_and_state = (
    sales_data.group_by(["year", "customer_state"])
    .agg(
        pl.sum("revenue").alias("Total revenue ('000)") / 1000,
        pl.sum("quantity").alias("Total products sold ('000)") / 1000,
    )
    .with_columns(
        (pl.col("Total revenue ('000)") / pl.col("Total products sold ('000)")).alias(
            "Average price"
        ),
        (pl.col("year") + 1).alias("next_year"),
    )
)

# join 2017 data with 2018 data, so we have both years side-to-side
joined = kpis_by_year_and_state.filter(pl.col("year") == 2017).join(
    kpis_by_year_and_state.filter(pl.col("year") == 2018),
    left_on=["customer_state", "next_year"],
    right_on=["customer_state", "year"],
    suffix="_next",
    how="outer",
)

# apply formulas (we don't need to worry about new/discontinued sales in this example)
effects = (
    joined.with_columns(
        (
            (pl.col("Average price_next") - pl.col("Average price"))
            * pl.col("Total products sold ('000)_next")
        ).alias("price_effect"),
        (
            (
                pl.col("Total products sold ('000)_next")
                - pl.col("Total products sold ('000)")
            )
            * pl.col("Average price")
        ).alias("volume_effect"),
    )
    .select(["customer_state", "price_effect", "volume_effect"])
    .sort("customer_state")
    .with_columns(
        (pl.col("price_effect") + pl.col("volume_effect")).alias("total_effect")
    )
)

print_table(effects)

customer_state      price_effect    volume_effect    total_effect
----------------  --------------  ---------------  --------------
AC                          -0.5             -5.6            -6.1
AL                          -6.2             -1.4            -7.6
AM                           1.1              1.4             2.6
AP                           0.8              0.9             1.7
BA                          21.5             29.6            51.1
CE                          -2.4              1.1            -1.2
DF                          -5.4             47.2            41.8
ES                          26.6             14.9            41.5
GO                           4.7             16.4            21.1
MA                           4.1             -2.5             1.6
MG                          42.6            123             165.7
MS                         -11.5             26.1            14.5
MT                         -10.7             14               3.2
PA                           9.1             -5.8             3.4
PB                          12.8              6.3            19.1
PE                           7.7             16.8            24.5
PI                           9                8.7            17.7
PR                          27.4             79.5           107
RJ                         -44.9             76.6            31.7
RN                          12.1              0.7            12.8
RO                           3.2             -7.3            -4.2
RR                           4.1              0.5             4.7
RS                           3.5             30.1            33.6
SC                          24.2             44.8            69
SE                           3.9             -8.5            -4.7
SP                         -14.2            924.3           910.1
TO                           0.4              3.9             4.2

In [14]:
print_table(effects.sum().drop("customer_state"))

  price_effect    volume_effect    total_effect
--------------  ---------------  --------------
         122.9           1435.9          1558.8

In [15]:
# | label: basic-pvm-calculation-side-by-side
# | fig-cap: "Calculating price and volume on an aggregate level vs. state level"
# | fig-alt: ""
# | layout-ncol: 1


totals = pl.concat(
    [
        pl.DataFrame(
            {
                "Calculation": "Aggregate level",
                "Price effect": price_effect,
                "Volume effect": volume_effect,
                "Total effect": price_effect + volume_effect,
            }
        ),
        effects.sum()
        .drop("customer_state")
        .with_columns(pl.lit("State-level").alias("Calculation"))
        .select(
            pl.col("Calculation"),
            pl.col("price_effect").alias("Price effect"),
            pl.col("volume_effect").alias("Volume effect"),
            pl.col("total_effect").alias("Total effect"),
        ),
    ]
)

print_table(totals)

Calculation        Price effect    Volume effect    Total effect
---------------  --------------  ---------------  --------------
Aggregate level            25.2           1533.6          1558.8
State-level               122.9           1435.9          1558.8

In [16]:
reference_price_and_volume = (
    totals_by_state.filter(pl.col("KPI") == "Total products sold ('000)")
    .select(
        pl.col("customer_state"),
        pl.col("% change").alias("volume_change, %"),
        pl.col("2017").alias("Volume 2017"),
    )
    .join(
        totals_by_state.filter(pl.col("KPI") == "Average price").select(
            pl.col("customer_state"), pl.col("2017").alias("2017 price")
        ),
        on="customer_state",
    )
)
c = alt.Chart(reference_price_and_volume).encode(
    alt.X("2017 price"),
    alt.Y("volume_change, %", title="% volume change"),
    alt.Color("customer_state", legend=None),
    alt.Tooltip("customer_state"),
    alt.Text("customer_state"),
)

(
    c.mark_point().encode(
        alt.Size("Volume 2017", legend=None),
    )
    + c.mark_text(size=8)
).properties(width=600, title="% volume change vs. starting price, by state")

alt.LayerChart(...)

From the above chart, it's pretty clear that it's what happened. Sao Paolo, in particular, is a low-priced state that had highest volume growth. More broadly, you can see a near perfectly linear relationship between change in volume and average price in the state - something the executive team could ponder about.

With all this data, now we can put together an even better chart that summarizes what is going on in the business. This part is more art than science - it's all about the storytelling. Here's one way we could do it.

In [17]:
top5_volume_effects = effects.sort(
    pl.col("volume_effect").abs(), descending=True
).to_dicts()[:5]
top5_price_effects = effects.sort(
    pl.col("price_effect").abs(), descending=True
).to_dicts()[:5]

In [18]:
state_volume_effect_total = effects["volume_effect"].sum()
state_price_effect_total = effects["price_effect"].sum()

chart_components = (
    [("2017", True, r2017)]
    + [
        (f"{state['customer_state']} volume effect", False, state["volume_effect"])
        for state in top5_volume_effects
    ]
    + [
        (
            "Other states - volume",
            False,
            state_volume_effect_total
            - sum([state["volume_effect"] for state in top5_volume_effects]),
        )
    ]
    + [
        (f"{state['customer_state']} price effect", False, state["price_effect"])
        for state in top5_price_effects
    ]
    + [
        (
            "Other states - price",
            False,
            state_price_effect_total
            - sum([state["price_effect"] for state in top5_price_effects]),
        )
    ]
    + [("2018", True, 0)]
)


pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=600, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [35]:
# | label: results-by-different-granularity
# | fig-cap: "Price and volume effects as a function of choice for unit of analysis"
# | fig-subcap: ""
# | fig-alt: ""
# | width: 100%
# | fig-align: center
# | layout-ncol: 1

defs = pvmf.TotalField(
    "revenue",
    "total",
    components=[
        pvmf.RateField(name="price"),
        pvmf.QuantityField("quantity"),
    ],
)

p = pvmc.PVM(
    sales_data.with_columns(
        pl.col("revenue") / 1000,
        pl.col("quantity") / 1000,
        (pl.col("revenue") / pl.col("quantity")).alias("price"),
    ),
    period_col="year",
    calculation_fields=defs,
)

results = []

for hierarchy_name, hierarchy_items in {
    "Aggregated": [],
    "Customer state": ["customer_state"],
    "Product category": ["product_category_name_english"],
    "Seller": ["seller_id"],
    "Product": ["product_id"],
    "Customer": ["customer_id"],
}.items():
    calculated = p.calculate(hierarchy=hierarchy_items, return_detail=False)
    results.append(
        p.summarize(calculated)
        .select(
            # pl.col("revenue").sum(),
            pl.col("price_effect").sum(),
            pl.col("quantity_effect").sum(),
            pl.col("total_effect").sum(),
        )
        .with_columns(pl.lit(hierarchy_name).alias("Calculation level"))
    )

full_results = pl.concat(results)
print_table(full_results)

  price_effect    quantity_effect    total_effect  Calculation level
--------------  -----------------  --------------  -------------------
          25.2             1533.6          1558.8  Aggregated
         122.9             1435.9          1558.8  Customer state
        -128.4             1687.2          1558.8  Product category
        -150.8             1709.5          1558.7  Seller
         -85.3             1644.1          1558.8  Product
           0               1558.8          1558.8  Customer

In [20]:
p.summarize(p.calculate(hierarchy=["seller_id"], return_detail=True))

shape: (3, 12)
┌────────────┬────────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────┐
│ status     ┆ status_rea ┆ quantity ┆ quantity_n ┆ … ┆ revenue_ch ┆ price_eff ┆ total_eff ┆ count │
│ ---        ┆ son        ┆ ---      ┆ ext        ┆   ┆ ange       ┆ ect       ┆ ect       ┆ ---   │
│ str        ┆ ---        ┆ f64      ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ u32   │
│            ┆ str        ┆          ┆ f64        ┆   ┆ f64        ┆ f64       ┆ f64       ┆       │
╞════════════╪════════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════╡
│ discontinu ┆            ┆ 4.3      ┆ 0.0        ┆ … ┆ -698.2     ┆ 0.0       ┆ -698.2    ┆ 582   │
│ ed         ┆            ┆          ┆            ┆   ┆            ┆           ┆           ┆       │
│ introduced ┆            ┆ 0.0      ┆ 14.8       ┆ … ┆ 2458.2     ┆ 0.0       ┆ 2458.2    ┆ 1240  │
│ like-for-l ┆            ┆ 44.4     ┆ 44.8       ┆ … ┆ -201.3     ┆ -150.8    ┆ -201.3    ┆ 1065  │
│ ike        ┆            ┆          ┆            ┆   ┆            ┆           ┆           ┆       │
└────────────┴────────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────┘

In [21]:
seller_table = (
    p.summarize(p.calculate(hierarchy=["seller_id"], return_detail=True))
    .with_columns(
        (pl.col("revenue") / pl.col("quantity")).alias("average_price"),
        (pl.col("revenue_next") / pl.col("quantity_next")).alias("average_price_next"),
    )
    .select(
        [
            "status",
            "revenue",
            "revenue_next",
            "average_price",
            "average_price_next",
            "quantity",
            "quantity_next",
            "quantity_effect",
            "price_effect",
        ]
    )
)

print_table(seller_table)

status           revenue    revenue_next    average_price    average_price_next    quantity    quantity_next    quantity_effect    price_effect
-------------  ---------  --------------  ---------------  --------------------  ----------  ---------------  -----------------  --------------
like-for-like     6107.4          5906.1            137.6                 131.8        44.4             44.8              -50.5          -150.8
discontinued       698.2             0              162.4                 nan           4.3              0               -698.2             0
introduced           0            2458.2            nan                   166.1         0               14.8             2458.2             0

In [137]:
existing_seller_mix

-256.3216216216211

In [145]:
existing_seller_mix = (
    seller_table.filter(pl.col("status") == "like-for-like")
    .select(
        (pl.col("average_price_next") - pl.col("average_price"))
        * pl.col("quantity_next")
    )
    .get_columns()[0][0] - full_results.filter(pl.col("Calculation level") == "Seller").get_column(
        "price_effect"
    )[0]
)

total_seller_mix = (
    full_results.filter(pl.col("Calculation level") == "Aggregated").get_column(
        "price_effect"
    )[0]
    - full_results.filter(pl.col("Calculation level") == "Seller").get_column(
        "price_effect"
    )[0]
)

new_disc_seller_mix = total_seller_mix - existing_seller_mix
price_effect_seller = seller_table["price_effect"].sum()

In [146]:
seller_chart_components = (
    [("2017", True, r2017)]
    + [
        ("Seller price effects", False, price_effect_seller),
        ("Existing seller mix", False, existing_seller_mix),
        ("Mix effect from seller entries/exits", False, new_disc_seller_mix),
        ("Overall volume increase", False, volume_effect),
    ]
    + [("2018", True, 0)]
)


pmv_charts.waterfall(seller_chart_components, labelAngle=-60).properties(
    width=600, title="Olist revenue bridge 2017-2018, seller perspective"
)

alt.LayerChart(...)

In [130]:
totals_by_seller = (
    sales_data.group_by(["year", "seller_id"])
    .agg(
        pl.sum("revenue").alias("Total revenue ('000)") / 1000,
        pl.sum("quantity").alias("Total products sold ('000)") / 1000,
    )
    .with_columns(
        (pl.col("Total revenue ('000)") / pl.col("Total products sold ('000)")).alias(
            "Average price"
        )
    )
)

ref = (
    totals_by_seller.drop_nulls()
    .with_columns(
        pl.when(pl.col("year") == 2017)
        .then(pl.col("Average price"))
        .min()
        .over(pl.col("seller_id"))
        .alias("2017_price")
    )
    .filter(
        (pl.col("Average price").min().over(pl.col("seller_id")) > 0)
        & (pl.col("2017_price").is_not_null())
    )
    .with_columns(
        pl.col("2017_price")
        .cut(range(50, 1000, 50), labels=[str(x) for x in range(0, 1000, 50)])
        .alias("2017_quantile")
    )
    .group_by(["year", "2017_quantile"])
    .agg(
        pl.col("Total revenue ('000)").sum(), pl.col("Total products sold ('000)").sum()
    )
    .with_columns(
        (
            pl.col("Total revenue ('000)")
            / pl.col("Total revenue ('000)").sum().over(pl.col("year"))
        ).alias("pct_rev"),
        (
            pl.col("Total products sold ('000)")
            / pl.col("Total products sold ('000)").sum().over(pl.col("year"))
        ).alias("pct_quantity"),
    )
)

alt.Chart(ref).mark_line().encode(
    alt.X("2017_quantile:Q"), alt.Color("year:O"), alt.Y("pct_quantity")
)

alt.Chart(...)

In [166]:
yr = (
    totals_by_seller.with_columns(
        pl.when(pl.col("year").count().over(pl.col("seller_id")) > 1)
        .then(pl.lit("existing"))
        .otherwise(pl.lit("new/exit"))
        .alias("seller_type")
    )
    .filter(pl.col("seller_type") == "existing")
    .select(
        pl.col("year"),
        pl.col("seller_id"),
        pl.col("Total revenue ('000)").alias("rev"),
        pl.col("Total products sold ('000)").alias("q"),
        pl.col("Average price").alias("price"),        
    ).with_columns(
        (pl.col('q') / pl.col('q').sum().over(pl.col('year'))).alias('q_share'),
        pl.col('q').sum().over(pl.col('year')).alias('total_q')
    )
)


s = yr.join(yr, on=["seller_id"], suffix="_next").filter(
    pl.col("year") == pl.col("year_next") - 1
).with_columns(
    ((pl.col('price_next') - pl.col('price')) * pl.col('q_next')).alias('pe'),
    ((pl.col('q_next') - pl.col('q')) * pl.col('price')).alias('qe'),
    ((pl.col('total_q_next') - pl.col('total_q')) * pl.col('price') * pl.col('q_share')).alias('total_qe'),
    ((pl.col('q_share_next') - pl.col('q_share')) * pl.col('price') * pl.col('total_q')).alias('mix_qe')
    
).with_columns(
    (pl.col('q_share_next') - pl.col('q_share')).alias("q_share_change")
)

alt.Chart(s).mark_bar().encode(
    alt.Y('mix_qe'),
    alt.X('seller_id', axis=alt.Axis(labels=False, ticks=False)),
    tooltip=['q', 'q_next', 'q_share', 'q_share_next', 'price']
).properties(width=500)

alt.Chart(...)

# Explicit mix effect calculation

Some PVM materials discuss formulas that calculate mix impact explictly. Again, I am not referring to the ones that call the "joint price and volume" effect as mix impact. That's just blatantly wrong. The explicit formulas are OK - but I am not a fan of them, you can get the same result by computing price/volume effects on different granularity levels and then comparing the results. In the old days of huge Excel spreadsheets where making multiple calculations was difficult, explicit mix formulas made sense. They make less sense when you're equipped with something like Python.

Nevertheless, it's a good way to develop intuition for PVM extensions beyond just price and volume calculations. The idea is very much the same - we need to find two variables, where volume mix is one of them, and then apply similar formulas to calculate the impact. 

With revenue, the two components were price and volume, and we established that if we have $i$ calculation units (e.g. states), we can get to revenue as:
$$ \text{Revenue} = \sum_{i=1}^{N}{\text{price}_{i} * \text{volume}_{i}} $$

Instead of having volume directly in the formula, we could instead write it this way:

$$ \text{Revenue} = \sum_{i=1}^{N}{\text{price}_{i} * (\sum{\text{volume}_{i}}} * \frac{\text{volume}_{i}}{\sum{\text{volume}_{i}}} ) $$

It's like a high school math trick. We took volume in a particular state $i$ and divided and multiplied it by total volume across the business. Now, however, we can think about the formula as having three components: price, total volume, and "share of volume". And what is mix impact? You guessed it, it's a change in share of volumes!

Let's we can update our formulas, so that in each case only one of the components is changing:

$$
\text{Price effect} = (\text{Price}_2 - \text{Price}_1) * \text{Quantity}_2 \\ 
\text{Volume effect} = (\text{Total Quantity}_2 - \text{Total Quantity}_1) * \text{Share of Quantity}_1 * \text{Price}_1 \\
\text{Mix effect} = (\text{Share of Quantity}_2 - \text{Share of Quantity}_1) * \text{Total Quantity}_1 * \text{Price}_1
$$

If we were to use these formulas to calculate effects, we would get `123k` for price effect (formula hasn't changed), `1533k` for volume effect (same as if we were to calculate volume effect on an aggregated data) and `-98k` for mix effect (exactly what we got when we compared the two sets of calculations above).

Confusing? Yeah, I know... I made a [quick spreadsheet](https://docs.google.com/spreadsheets/d/1fDR5vNHIOO0MfBQPC69R9moflt5fR8MwWI2IpD0Wirs/edit?usp=sharing) with the above calculations - if you're really determined, you may want to check it out. Confusion isn't the only reason I am not a fan of these formulas. The other reason is that mix impact does not have a good meaning on a individual calculation unit level. Let's take Sao Paolo. Our analysis shows that the volume growth in it contributed `924k` in revenue. Using the 3-component formula, we get that `924k` is now broken down into `538k` in volume effect and `386k` in mix effect. But what does it mean? Also, we concluded that the overall mix effect was negative (`-98k`), and we know that Sao Paolo was the main reason for it - its growth brought our average prices down. How can its mix effect be positive? What is going on? 

The answer, in brief, is that mix effects by state are affecting each other. If share of volume of one state goes up, then, by definition, some other states will see their share decline. And that's why you can't really look at them separately. It's possible to wrap your head aroud their meaning - but the chances of communicating them effectively to a business person are really low. My advice is to avoid doing that. We'll return to a better way to look at mix impacts later on.

## Turtles all the way down

Now that we're clear with the mechanics behind PVM, let's turn to the the most important aspect of the analysis, which, if not chosen carefully, make the output of it, at a minimum, hard to interpret, and worst - complete rubbish. And it's not "which formula variation to use". Instead, the choice that's most important is the one of the unit of analysis.

So far, we did calculations on an aggregate level and on a customer-based geography level. But we have access to so many more dimensions in this data! We could analyse price and volume dynamics by:
* Seller geography or even individual seller
* Product category or even individual product
* Individual customer
* A combination of the above factors

What's the right choice? For one, it's not necessarily the most granular level possible. Suppose we calculated effects on individual customer ID / seller ID / product ID combination. In that case, we would only capture price effects in situations where the same customer bought the same product from the same seller. Everything else would count as volume effects. That doesn't sound very appropriate. In fact, in this particular dataset, not a single customer appears in multiple years (probably a function of anonymization), so it definitely would not work.

You could take a product-first perspective: it doesn't matter who buys it and from whom they buy it, price effects should capture pricing changes in individual products. This approach could be appropriate for a company that sells products that don't change often. E.g., your local bakery. You could calculate it PMV effects on every cookie, coffee and lunch item variation and the total price effects would likely represent price inflation. But in an e-commerce marketplace, a lot individual products are shortlived. If we were to do PVM analysis on a product ID level, we would get this:

In [43]:
defs = pvmf.TotalField(
    "revenue",
    "total",
    components=[
        pvmf.RateField(name="price"),
        pvmf.QuantityField("quantity"),
    ],
)

p = pvmc.PVM(
    sales_data.with_columns(pl.col("revenue") / 1000, pl.col("quantity") / 1000),
    period_col="year",
    calculation_fields=defs,
)
hierarchy = ["product_id"]

calculated = p.calculate(hierarchy=hierarchy, return_detail=True)

In [ ]:
chart_components = itt.chain(
    [("2017", True, r2017)],
    p.find_largest_components(calculated, "product_id", max_components=0),
    [("2018", True, 0)],
)

pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=650, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [ ]:
print_table(p.summarize(calculated))

+---------------+---------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+
|    status     | status_reason | revenue | revenue_next | revenue_change | quantity_effect | price_effect | total_effect | count |
+---------------+---------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+
| like-for-like |               | 3092.5  |    3312.4    |     219.9      |      288.2      |    -114.4    |    173.8     | 4854  |
| discontinued  |  product_id   | 3713.0  |     0.0      |    -3713.0     |     -3713.0     |     0.0      |   -3713.0    | 11569 |
|  introduced   |  product_id   |   0.0   |    5051.9    |     5051.9     |     5051.9      |     0.0      |    5051.9    | 15063 |
+---------------+---------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+

Now, it could be that that's the story you want to tell: we're seeing a large product churn in the business, while the products that stay on the marketplace saw a volume increase, offset by lower prices. However, given that products that stay year-on-year account for less than 50% of total revenue, it may not be a good choice. There's a good chance that the relatively high negative price we're seeing is because of substitution effects: newly introduced products are effectively replacements for existing products, and the latter are then sold at lower prices to clear the inventory. 

Imagine we were selling phones - when iPhone 20 is released, the price of iPhone 19 will typically go down. But should this be reflected as a "price effect"? That's just product portfolio change. In this case, we may be more interested in capturing price changes across the entire phone SKU portfolio, acknowledging that price effects will be a function of deliberate pricing changes as well as the change in the mix of phone SKU portfolio. 

Unfortunately, the dataset does not have categorization of products on that level of detail. Instead, we only have broad categories. Let's see what happens if we use those.

In [ ]:
imp.reload(pmv_charts)
hierarchy = ["product_category_name_english"]

calculated = p.calculate(hierarchy=hierarchy, return_detail=False)

chart_components = list(
    itt.chain(
        [("2017", True, r2017)],
        p.find_largest_components(calculated, hierarchy[0], max_components=5),
        [("2018", True, 0)],
    )
)

pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=650, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [ ]:
print_table(p.summarize(calculated))

+---------------+-------------------------------+---------+-----------------+--------------+--------------+-------+
|    status     |         status_reason         | revenue | quantity_effect | price_effect | total_effect | count |
+---------------+-------------------------------+---------+-----------------+--------------+--------------+-------+
| like-for-like |                               | 6805.2  |     1465.2      |    -184.5    |    1280.8    |  70   |
| discontinued  | product_category_name_english |   0.3   |      -0.3       |     0.0      |     -0.3     |   1   |
+---------------+-------------------------------+---------+-----------------+--------------+--------------+-------+

Now we are starting to see some interesting dynamics. First of all, price effect is highly negative (-185M), and it appears that there are two specific product categories - computer accessories & watches - where price decreases are concentrated. Given our unit of analysis, it could represent a shift of mix towards lower-priced product subcategories (e.g. more keyboard sales than monitor sales), but it nevertheless is an interesting dynamic. We can also see which product categories account for the majority of the volume growth: watches, health & beauty, computer accessories and auto are the main drivers.

A completely different perspective would be to argue that Olist is primarily about sellers. We should thus analyse its growth first by understanding if we are gaining/losing sellers and what happens to their sales. In fact, we could combine both seller- and product- perspectives.

In [ ]:
imp.reload(pmv_charts)
hierarchy = ["seller_id", "product_category_name_english"]

calculated = p.calculate(hierarchy=hierarchy, return_detail=False)

chart_components = list(
    itt.chain(
        [("2017", True, r2017)],
        p.find_largest_components(calculated, hierarchy[1], max_components=5),
        [("2018", True, 0)],
    )
)

pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=650, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [ ]:
print_table(p.summarize(calculated))

+---------------+-----------------------------------------+---------+-----------------+--------------+--------------+-------+
|    status     |              status_reason              | revenue | quantity_effect | price_effect | total_effect | count |
+---------------+-----------------------------------------+---------+-----------------+--------------+--------------+-------+
|  introduced   | seller_id,product_category_name_english |   0.0   |      449.7      |     0.0      |    449.7     |  725  |
|  introduced   |                seller_id                |   0.0   |     2458.2      |     0.0      |    2458.2    | 2151  |
| discontinued  |                seller_id                |  698.2  |     -698.2      |     0.0      |    -698.2    |  852  |
| discontinued  | seller_id,product_category_name_english |  308.4  |     -308.4      |     0.0      |    -308.4    |  604  |
| like-for-like |                                         | 5799.0  |     -261.3      |    -98.4     |    -359.8    | 1770  |
+---------------+-----------------------------------------+---------+-----------------+--------------+--------------+-------+

The chart labels that my WIP package spits out are imperfect, so let's take it step by step:

 * The biggest driver to revenue increase, it turns out, are sellers. New sellers contributed +2.458M in sales, offset by 698k lost sales from sellers that stopped using the platform.
 * Additionally, existing sellers saw a net positive effect from changes in the breadth of their portfolios. New product categories entered by existing sellers contributed 449k, offset by 308k of "category exits". 
 * The price and volume effects among existing sellers selling in existing product categories were, overall, quite limited in coparison to seller-driven effects. Additionally, turns out both of them were negative: total volume effect among these items was -261k, and price effect -98k. Watches & gifts, a category that seemed to be of high-growth before, now shows up as with highest negative volume effects!

It may seem that PVM analysis gives contradicting results every time. But what really is happening is that our chosen unit of analysis allows getting a different perspective into what's happening in Olist. If you were to sit back and think what kind of big picture all these analyses tell you, you could conclude something like this:
* Revenue growth in Olist was primarily driven by influx of new sellers;
* New sellers cannibalized existing sellers' sales - leading to volume decreases - and forcing sellers to lower prices in order to be able to compete.

In [ ]:
imp.reload(pmv_charts)
hierarchy = [
    "product_category_name_english",
    "seller_id",
    "product_id",
]

calculated = p.calculate(hierarchy=hierarchy, return_detail=False)

chart_components = list(
    itt.chain(
        [("2017", True, r2017)],
        p.find_largest_components(calculated, hierarchy[0], max_components=5),
        [("2018", True, 0)],
    )
)

pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=650, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [ ]:
print_table(p.summarize(calculated))

+---------------+----------------------------------------------------+---------+-----------------+--------------+--------------+-------+
|    status     |                   status_reason                    | revenue | quantity_effect | price_effect | total_effect | count |
+---------------+----------------------------------------------------+---------+-----------------+--------------+--------------+-------+
| discontinued  | product_category_name_english,seller_id,product_id | 2929.3  |     -2929.3     |     0.0      |   -2929.3    | 9291  |
|  introduced   |      product_category_name_english,seller_id       |   0.0   |     2908.0      |     0.0      |    2908.0    | 7527  |
|  introduced   | product_category_name_english,seller_id,product_id |   0.0   |     2575.1      |     0.0      |    2575.1    | 8605  |
| discontinued  |           product_category_name_english            |   0.3   |      -0.3       |     0.0      |     -0.3     |   2   |
| discontinued  |      product_category_name_english,seller_id       | 1006.2  |     -1006.2     |     0.0      |   -1006.2    | 2926  |
| like-for-like |                                                    | 2869.7  |       7.4       |    -20.9     |    -13.5     | 4569  |
+---------------+----------------------------------------------------+---------+-----------------+--------------+--------------+-------+

## Zooming in

Let's take one particular product category - Watches & gifts and look a bit closer.

In [ ]:
calculated.filter(pl.col("product_category_name_english") == "watches_gifts").select(
    cs.contains("effect")
)

shape: (1, 3)
┌─────────────────┬──────────────┬──────────────┐
│ quantity_effect ┆ price_effect ┆ total_effect │
│ ---             ┆ ---          ┆ ---          │
│ f64             ┆ f64          ┆ f64          │
╞═════════════════╪══════════════╪══════════════╡
│ 299.20548       ┆ -86.96099    ┆ 212.24449    │
└─────────────────┴──────────────┴──────────────┘

In [ ]:
hierarchy = ["product_category_name_english", "product_id"]

watches = p.calculate(hierarchy=hierarchy, return_detail=True).filter(
    pl.col("product_category_name_english") == "watches_gifts"
)

watches_2017 = watches.select(pl.col("revenue").sum()).item()
chart_components = list(
    itt.chain(
        [("2017", True, watches_2017)],
        p.find_largest_components(watches, hierarchy[1], max_components=0),
        [("2018", True, 0)],
    )
)

pmv_charts.waterfall(chart_components, labelAngle=-60).properties(
    width=650, title="Olist revenue bridge 2017-2018"
)

alt.LayerChart(...)

In [ ]:
watches.group_by("status").agg(
    pl.col("quantity").sum(),
    pl.col("revenue").sum(),
    pl.col("quantity_next").sum(),
    pl.col("revenue_next").sum(),
).with_columns(
    (pl.col("revenue") / pl.col("quantity")).alias("avg_price"),
    (pl.col("revenue_next") / pl.col("quantity_next")).alias("avg_price_next"),
)

shape: (3, 7)
┌───────────────┬──────────┬───────────┬───────────────┬──────────────┬────────────┬───────────────┐
│ status        ┆ quantity ┆ revenue   ┆ quantity_next ┆ revenue_next ┆ avg_price  ┆ avg_price_nex │
│ ---           ┆ ---      ┆ ---       ┆ ---           ┆ ---          ┆ ---        ┆ t             │
│ str           ┆ f64      ┆ f64       ┆ f64           ┆ f64          ┆ f64        ┆ ---           │
│               ┆          ┆           ┆               ┆              ┆            ┆ f64           │
╞═══════════════╪══════════╪═══════════╪═══════════════╪══════════════╪════════════╪═══════════════╡
│ introduced    ┆ 0.0      ┆ 0.0       ┆ 1.108         ┆ 352.18992    ┆ NaN        ┆ 317.860939    │
│ discontinued  ┆ 0.739    ┆ 254.58132 ┆ 0.0           ┆ 0.0          ┆ 344.494344 ┆ NaN           │
│ like-for-like ┆ 1.488    ┆ 257.21965 ┆ 2.52          ┆ 397.54852    ┆ 172.862668 ┆ 157.757349    │
└───────────────┴──────────┴───────────┴───────────────┴──────────────┴────────────┴───────────────┘

In [ ]:
print_table(p.summarize(watches))

+---------------+------------------------------------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+
|    status     |              status_reason               | revenue | revenue_next | revenue_change | quantity_effect | price_effect | total_effect | count |
+---------------+------------------------------------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+
| discontinued  | product_category_name_english,product_id |  254.6  |     0.0      |     -254.6     |     -254.6      |     0.0      |    -254.6    |  460  |
| like-for-like |                                          |  257.2  |    397.5     |     140.3      |      199.6      |    -75.4     |    124.2     |  264  |
|  introduced   | product_category_name_english,product_id |   0.0   |    352.2     |     352.2      |      352.2      |     0.0      |    352.2     |  573  |
+---------------+------------------------------------------+---------+--------------+----------------+-----------------+--------------+--------------+-------+